export const ARTBOARD_WIDTH = 1800;
export const ARTBOARD_HEIGHT = 3200;

export const homeAssets = {
  backgroundBase: require("../../assets/figma/home/backgroundBase.png"),
  backgroundDetail: require("../../assets/figma/home/backgroundDetail.png"),
  topBackground: require("../../assets/figma/home/topBackground.png"),
  attributeChartBase: require("../../assets/figma/home/attributeChartBase.png"),
  attributeChartRadar: require("../../assets/figma/home/attributeChartRadar.png"),
  attributeChartLine1: "https://www.figma.com/api/mcp/asset/d046acf8-b30d-4dcf-891e-c085dded6e26",
  attributeChartLine2: "https://www.figma.com/api/mcp/asset/2d6b89a6-1b63-45dc-bfcd-9c4f6e3292d1",
  attributeChartLine3: "https://www.figma.com/api/mcp/asset/a2d1b473-328f-4deb-b284-4968d1ea5a74",
  attributeChartLine4: "https://www.figma.com/api/mcp/asset/b5cca432-66cb-4861-a96d-8b2679c4ac80",
  attributeChartLine5: "https://www.figma.com/api/mcp/asset/b822a163-b6ee-4853-a7c9-fb49f33d4cff",
  attributeChartOutline: "https://www.figma.com/api/mcp/asset/e9380a59-3897-409b-8f4f-c8de7a03172a",
  attributeChartOutline2: "https://www.figma.com/api/mcp/asset/ecffaaee-e0c3-40ce-90dc-dfbacc3f82ed",
  mechCardMask: require("../../assets/figma/home/mechCardMask.png"),
  mechCardFill: "https://www.figma.com/api/mcp/asset/1b84264c-785b-4b0f-a79f-a5c45f324583",
  expBarTotal: "https://www.figma.com/api/mcp/asset/45cee574-deed-4a99-a665-e7cff8d379f3",
  expBarProgress: "https://www.figma.com/api/mcp/asset/d45035a5-565a-494e-9066-f9849811d272",
  changeBar: "https://www.figma.com/api/mcp/asset/9bc1f51f-d4c1-4478-ba93-83072966a08e",
  changeIconBack: require("../../assets/figma/home/changeIconBack.png"),
  changeIconFront: require("../../assets/figma/home/changeIconFront.png"),
  abilityChipBackground1: require("../../assets/figma/home/abilityChipBackground1.png"),
  abilityChipDetail1: require("../../assets/figma/home/abilityChipDetail1.png"),
  abilityChipBackground3: require("../../assets/figma/home/abilityChipBackground3.png"),
  abilityChipDetail3: require("../../assets/figma/home/abilityChipDetail3.png"),
  bottomBackground: require("../../assets/figma/home/bottomBackground.png"),
  marketplaceIcon: require("../../assets/figma/home/marketplaceIcon.png"),
  syncIcon: require("../../assets/figma/home/syncIcon.png"),
  inventoryIcon: require("../../assets/figma/home/inventoryIcon.png"),
  arenaIcon: require("../../assets/figma/home/arenaIcon.png")
};

export const fitnessAssets = {
  backgroundBase: require("../../assets/figma/fitness/backgroundBase.png"),
  backgroundDesign: require("../../assets/figma/fitness/backgroundDesign.png"),
  syncPointBar: require("../../assets/figma/fitness/syncPointBar.png"),
  syncPointAccent: require("../../assets/figma/fitness/syncPointAccent.png"),
  goalMask: require("../../assets/figma/fitness/goalMask.png"),
  goalFill: require("../../assets/figma/fitness/goalFill.png"),
  goalBarBack: "https://www.figma.com/api/mcp/asset/aa1af00c-d371-43f0-b5c0-f78c13e72077",
  goalBarFill: "https://www.figma.com/api/mcp/asset/0d50be0a-9f37-49e5-8dda-c0caa23e85be",
  mechMask: require("../../assets/figma/fitness/mechMask.png"),
  mechFill: "https://www.figma.com/api/mcp/asset/d6bb944f-860f-42d2-b858-35b51f98d64c",
  mechExpBack: "https://www.figma.com/api/mcp/asset/0418f140-1059-4b0e-b580-7fee5622eca1",
  mechExpFill: "https://www.figma.com/api/mcp/asset/afb9ed62-a2a8-4ebb-91fc-1d03cf6477ca",
  changeBar: "https://www.figma.com/api/mcp/asset/827f0c37-6b3a-45da-9e12-923cf33d4439",
  changeIconBack: require("../../assets/figma/fitness/changeIconBack.png"),
  changeIconFront: require("../../assets/figma/fitness/changeIconFront.png"),
  speedometerMask: require("../../assets/figma/fitness/speedometerMask.png"),
  speedometerFill: require("../../assets/figma/fitness/speedometerFill.png"),
  speedometerNeedle: require("../../assets/figma/fitness/speedometerNeedle.png"),
  distanceMask: require("../../assets/figma/fitness/distanceMask.png"),
  distanceFill: require("../../assets/figma/fitness/distanceFill.png"),
  rewardSync: require("../../assets/figma/fitness/rewardSync.png"),
  rewardHolos: require("../../assets/figma/fitness/rewardHolos.png"),
  rewardExp: require("../../assets/figma/fitness/rewardExp.png"),
  bottomElement: require("../../assets/figma/fitness/bottomElement.png"),
  goButton: require("../../assets/figma/fitness/goButton.png")
};
